# Generated by Django 5.2.7 on 2026-01-03 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criminology', '0005_alter_students_studentschoolid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='studentid',
            field=models.IntegerField(),
        ),
    ]
